# a git repo containing pre-commit plugins must contain a
# .pre-commit-hooks.yaml file that tells pre-commit which hooks are provided
# more details at https://pre-commit.com/#creating-new-hooks

- id: say-hello
  name: say hello
  description: a template to show how to implement a pre-commit hook
  language: python
  entry: say-hello
  require_serial: true
  pass_filenames: false
  args: ['OpenMMLab']

- id: check-algo-readme
  name: check algorithm readme
  description: check whether the abstract and icon exist in the algorithm readme
  language: python
  entry: check-algo-readme
  require_serial: true
  pass_filenames: false

- id: check-copyright
  name: check copyright
  description: check whether the code contains copyright
  language: python
  entry: check-copyright
  require_serial: true
  pass_filenames: false

- id: check-ecosystem-validity
  name: check ecosystem validity
  description: check validity of yaml
  language: python
  entry: check-ecosystem-validity
  types: [yaml]
  require_serial: false
  pass_filenames: false
  additional_dependencies:
  - cerberus

- id: remove-improper-eol-in-cn-docs
  name: remove improper eol in cn docs
  description: Remove the end_of_line characters that split natural paragraphs in Chinese docs
  entry: remove_eol_characters
  language: python
  files: .*\.md$
  pass_filenames: true
  require_serial: true
